# backend/app/api/routes/logs.py
#
# Responsibility: HTTP route handlers for water-log creation and history.
#
# Endpoints:
#   POST /api/logs                        — record a single sensor reading
#   GET  /api/sensors/{sensor_id}/history — paginated reading history
#
# ─── 404 vs 422 distinction ──────────────────────────────────────────────────
# POST /api/logs can return two different 4xx codes:
#
#   422 Unprocessable Entity:
#       Pydantic validation failed — wrong field types, out-of-bounds values.
#       E.g.: {"sensor_id": "abc"}  or  {"water_level": 99999}
#       Generated automatically by FastAPI before the handler runs.
#
#   404 Not Found:
#       sensor_id passed validation (is a valid int) but does not exist in DB.
#       E.g.: {"sensor_id": 99999, "water_level": 0.5} — valid but unknown sensor.
#       Generated by this handler when the service raises ValueError.
#
# This distinction matters for API consumers:
#   - 422 → fix the request format
#   - 404 → the sensor doesn't exist, use a valid sensor_id
#
# ─── Pagination parameters (Query) ───────────────────────────────────────────
# FastAPI's Query() lets us:
#   - Declare default values (page=1, page_size=50)
#   - Add server-side bounds validation (ge=1, le=200)
#   - Include descriptions in the OpenAPI spec
#
# These constraints duplicate the schema bounds in HistoryResponse but are
# necessary here to reject bad requests BEFORE the DB query executes.

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logger import get_logger
from app.dependencies.database import get_db
from app.schemas.water_log import (
    HistoryResponse,
    WaterLogCreate,
    WaterLogCreateResponse,
    WaterLogResponse,
)
from app.services.water_log_service import create_water_log, get_sensor_history

logger = get_logger(__name__, log_file="backend.log")

router = APIRouter(tags=["Water Logs"])


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/logs
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/logs",
    response_model=WaterLogCreateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Record a water-level reading",
    description=(
        "Insert a single water-level reading for a registered sensor.\n\n"
        "**Validation chain:**\n"
        "1. Pydantic validates the request body (correct types, value bounds).\n"
        "2. The service layer verifies the `sensor_id` exists in the DB.\n"
        "3. The record is inserted and the DB-assigned timestamp is returned.\n\n"
        "**Timestamp:** Set by the database server, not the client, "
        "to avoid clock-skew issues with IoT devices."
    ),
    responses={
        201: {"description": "Water log created successfully."},
        404: {"description": "sensor_id does not exist in the sensors table."},
        422: {"description": "Invalid request body — check field types and bounds."},
        500: {"description": "Database insert failed."},
    },
)
async def create_log(
    payload: WaterLogCreate,
    db: AsyncSession = Depends(get_db),
) -> WaterLogCreateResponse:
    """
    POST /api/logs

    Body: {"sensor_id": 1, "water_level": 0.72}

    Async flow:
        1. Pydantic deserialises and validates the JSON body.         (auto)
        2. create_water_log(db, payload) is awaited:
               - COUNT check: does sensor_id exist?                   (async SELECT)
               - If not: raise ValueError → this handler returns 404
               - If yes: INSERT + commit + refresh                    (async INSERT)
        3. WaterLogResponse is constructed from the ORM instance.
        4. HTTP 201 is returned with the created record.

    Error mapping:
        ValueError       → 404 Not Found (sensor does not exist)
        Any other error  → 500 Internal Server Error
    """
    try:
        log = await create_water_log(db, payload)
    except ValueError as exc:
        logger.warning(
            "POST /api/logs rejected — sensor_id=%d not found: %s",
            payload.sensor_id,
            exc,
        )
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error":  "Sensor not found",
                "detail": str(exc),
            },
        )
    except Exception as exc:
        logger.error("POST /api/logs failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error":  "Database insert failed",
                "detail": str(exc),
            },
        )

    log_response = WaterLogResponse.model_validate(log)
    logger.info(
        "POST /api/logs -> created log id=%d sensor_id=%d.",
        log.id,
        log.sensor_id,
    )

    return WaterLogCreateResponse(
        success=True,
        message=f"Water log recorded for sensor {payload.sensor_id}.",
        log=log_response,
    )


# ─────────────────────────────────────────────────────────────────────────────
# GET /api/sensors/{sensor_id}/history
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/sensors/{sensor_id}/history",
    response_model=HistoryResponse,
    status_code=status.HTTP_200_OK,
    summary="Get paginated reading history for a sensor",
    description=(
        "Returns paginated water-level readings for a specific sensor, "
        "ordered by timestamp descending (newest first).\n\n"
        "**Pagination:**\n"
        "- `page`: Page number starting at 1.\n"
        "- `page_size`: Records per page, max 200.\n"
        "- Response includes `total` for computing total pages.\n\n"
        "**Example:** `GET /api/sensors/1/history?page=2&page_size=25`\n\n"
        "**Frontend page count:** `ceil(total / page_size)`"
    ),
    responses={
        200: {"description": "History returned. May be empty if no logs exist yet."},
        404: {"description": "Sensor with the given ID does not exist."},
        422: {"description": "Invalid page or page_size parameter."},
        500: {"description": "Database query failed."},
    },
)
async def get_history(
    sensor_id: int,
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed). First page = 1.",
        examples=[1, 2, 10],
    ),
    page_size: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Number of records per page. Max 200.",
        examples=[10, 50, 100],
    ),
    db: AsyncSession = Depends(get_db),
) -> HistoryResponse:
    """
    GET /api/sensors/{sensor_id}/history?page=1&page_size=50

    Async flow:
        1. FastAPI validates sensor_id (int path param) and query params.
        2. get_sensor_history(db, sensor_id, page, page_size) is awaited:
               - SELECT sensor → 404 if not found
               - COUNT(*) for total rows
               - SELECT ... ORDER BY timestamp DESC OFFSET x LIMIT y
        3. Each WaterLog ORM instance → WaterLogResponse via model_validate.
        4. HistoryResponse is returned with pagination metadata.

    Chronological ordering:
        Records are newest-first (DESC).  This matches dashboard patterns
        where operators want the most recent flood levels at the top.
        Frontend chart libraries can reverse the order trivially if needed.
    """
    try:
        logs, total = await get_sensor_history(
            db,
            sensor_id=sensor_id,
            page=page,
            page_size=page_size,
        )
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error":  "Sensor not found",
                "detail": str(exc),
            },
        )
    except Exception as exc:
        logger.error(
            "GET /api/sensors/%d/history failed: %s", sensor_id, exc, exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error":  "Database query failed",
                "detail": str(exc),
            },
        )

    history_items = [WaterLogResponse.model_validate(log) for log in logs]
    logger.info(
        "GET /api/sensors/%d/history -> page=%d records=%d total=%d.",
        sensor_id,
        page,
        len(history_items),
        total,
    )

    return HistoryResponse(
        sensor_id=sensor_id,
        total=total,
        page=page,
        page_size=page_size,
        history=history_items,
    )
