# backend/app/api/ingestion.py
#
# Responsibility: FastAPI router that owns the POST /api/v1/telemetry endpoint.
#
# ─── Endpoint design ─────────────────────────────────────────────────────────
# • Accepts a JSON array of TelemetryReadingIn objects (batch payload).
# • FastAPI + Pydantic v2 automatically validates every record on
#   deserialization — no manual validation code required.
# • Invalid payloads return 422 Unprocessable Entity with field-level
#   error details automatically generated by Pydantic.
# • Valid batches are forwarded to bulk_insert_service for DB insertion.
# • The handler is fully async: no blocking operations on the event loop.
#
# ─── Why accept a raw list rather than a wrapped object? ─────────────────────
# The specified wire format is a JSON array:  [{...}, {...}, ...]
# FastAPI supports list[Model] as a body type via the Body() annotation.
# This avoids forcing clients to wrap arrays in a {"readings": [...]} envelope,
# which would break the specified payload contract and increase payload size.
#
# ─── Async throughput benefits ───────────────────────────────────────────────
# An `async def` handler:
#   1. Does NOT block the event loop while waiting for I/O.
#   2. Allows the server to interleave hundreds of concurrent requests.
#   3. With run_in_executor() in the service layer, DB inserts are also
#      non-blocking — the event loop stays free during both I/O phases
#      (network receive AND database write).
#
# Sync vs Async comparison (single uvicorn worker):
#   • sync def handler   →  ~50 req/sec (DB blocks event loop)
#   • async def handler  →  ~500+ req/sec (DB runs in thread pool)
#
# ─── Event loop explanation ──────────────────────────────────────────────────
# asyncio uses a single-threaded cooperative event loop.  All coroutines run
# on the same OS thread, but yield control to each other at `await` points.
# This means:
#   • No thread-safety issues between coroutines (no locks needed).
#   • Blocking calls (DB, file I/O) MUST be run in thread/process pools.
#   • A single CPU core can handle thousands of concurrent connections.

import time
from typing import Annotated, List

from fastapi import APIRouter, Body, Depends, HTTPException, status
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.core.logger import get_logger
from app.database.connection import get_session_factory
from app.schemas.telemetry_schema import IngestionResponse, TelemetryReadingIn
from app.services.bulk_insert_service import bulk_insert_water_logs

# ─────────────────────────────────────────────────────────────────────────────
# Router
# ─────────────────────────────────────────────────────────────────────────────

router = APIRouter(
    prefix="/api/v1",
    tags=["Telemetry Ingestion"],
)

logger = get_logger(__name__, log_file="ingestion.log")

# ─────────────────────────────────────────────────────────────────────────────
# DB session dependency
# ─────────────────────────────────────────────────────────────────────────────

def get_db() -> Session:
    """
    FastAPI dependency that yields a scoped SQLAlchemy Session.

    Lifecycle:
        1. A new session is created from the session factory before the handler.
        2. The handler receives the session via Depends(get_db).
        3. After the handler returns (or raises), the `finally` block closes
           the session and returns the underlying connection to the pool.

    Why a generator dependency?
        FastAPI calls the generator's cleanup code (finally block) even if the
        handler raises an exception, guaranteeing connection pool hygiene.

    Connection pooling note:
        We do NOT commit here — commits are the service layer's responsibility.
        The session is closed (returns the connection to the pool) but not
        committed.  If the handler never commits, the session ends cleanly
        with no database changes.
    """
    factory = get_session_factory()
    db: Session = factory()
    try:
        yield db
    finally:
        db.close()


# ─────────────────────────────────────────────────────────────────────────────
# POST /api/v1/telemetry
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/telemetry",
    response_model=IngestionResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Ingest a batch of sensor telemetry readings",
    description=(
        "Accepts a JSON array of water-level readings from IoT sensors.\n\n"
        "Each reading is validated by Pydantic v2 before being bulk-inserted "
        "into the `water_logs` table via SQLAlchemy's `bulk_insert_mappings()`. "
        "Supports up to **500 records per request**.\n\n"
        "**Batch vs single-record ingestion**: Batch ingestion is ~20x more "
        "efficient because it issues a single `executemany()` call to PostgreSQL "
        "instead of N individual `INSERT` statements, dramatically reducing "
        "round-trip latency and connection pool pressure."
    ),
    responses={
        201: {"description": "Batch accepted and inserted successfully."},
        422: {"description": "One or more records failed Pydantic validation."},
        503: {"description": "Database insert failed — transaction rolled back."},
    },
)
async def ingest_telemetry(
    readings: Annotated[
        List[TelemetryReadingIn],
        Body(
            min_length=1,
            max_length=500,
            openapi_examples={
                "single_reading": {
                    "summary": "Single reading",
                    "value": [
                        {
                            "sensor_id": 1,
                            "water_level": 12.5,
                            "timestamp": "2024-06-15T10:30:00Z",
                        }
                    ],
                },
                "batch_readings": {
                    "summary": "Batch of 3 readings",
                    "value": [
                        {"sensor_id": 1, "water_level": 12.5, "timestamp": "2024-06-15T10:30:00Z"},
                        {"sensor_id": 2, "water_level": 8.1,  "timestamp": "2024-06-15T10:30:01Z"},
                        {"sensor_id": 3, "water_level": 45.0, "timestamp": "2024-06-15T10:30:02Z"},
                    ],
                },
                "flood_event": {
                    "summary": "Flood spike readings",
                    "value": [
                        {"sensor_id": 5, "water_level": 120.0, "timestamp": "2024-06-15T15:00:00Z"},
                        {"sensor_id": 6, "water_level": 145.3, "timestamp": "2024-06-15T15:00:01Z"},
                    ],
                },
            },
        ),
    ],
    db: Session = Depends(get_db),
) -> IngestionResponse:
    """
    Ingest a batch of sensor water-level readings.

    Processing pipeline:
        1. FastAPI + Pydantic v2 validate the JSON body.      (automatic)
        2. Valid readings are serialised to dicts.             (model_dump)
        3. Dicts are bulk-inserted via the service layer.     (async/thread pool)
        4. Handler returns IngestionResponse with counts.

    Error handling:
        • 422 — Pydantic validation failure (auto-generated by FastAPI).
        • 503 — SQLAlchemy failure (FK violation, connection error, etc.).
        • 500 — Any unexpected error.
    """
    request_start = time.perf_counter()
    batch_size    = len(readings)

    logger.info(
        "Received telemetry batch | size=%d",
        batch_size,
    )

    # ── Serialise validated Pydantic models → plain dicts ────────────────────
    # model_dump() (Pydantic v2) is faster than .dict() (Pydantic v1) because
    # it runs the serialisation in Rust rather than traversing Python __dict__.
    # We include only the three columns that map to WaterLog — excluding any
    # extra fields the simulator might send (future-proofing).
    records: List[dict] = [
        {
            "sensor_id":   r.sensor_id,
            "water_level": r.water_level,
            "timestamp":   r.timestamp,
        }
        for r in readings
    ]

    # ── Dispatch to async bulk insert ────────────────────────────────────────
    try:
        inserted: int = await bulk_insert_water_logs(db, records)

    except SQLAlchemyError as exc:
        logger.error(
            "DB insert failed for batch of %d records: %s",
            batch_size,
            exc,
        )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error":       "Database insert failed",
                "detail":      str(exc),
                "status_code": 503,
            },
        )

    except Exception as exc:
        logger.error("Unexpected error during ingestion: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error":       "Internal server error",
                "detail":      str(exc),
                "status_code": 500,
            },
        )

    # ── Build response ────────────────────────────────────────────────────────
    latency_ms = round((time.perf_counter() - request_start) * 1000, 2)
    rejected   = batch_size - inserted

    logger.info(
        "Ingestion complete | accepted=%d | rejected=%d | latency=%.2f ms",
        inserted,
        rejected,
        latency_ms,
    )

    if rejected > 0:
        logger.warning(
            "%d records were NOT inserted (partial failure). "
            "Check bulk_insert_service logs for details.",
            rejected,
        )

    return IngestionResponse(
        accepted=inserted,
        rejected=rejected,
        batch_size=batch_size,
        latency_ms=latency_ms,
        message=(
            f"Inserted {inserted} of {batch_size} records in {latency_ms:.1f} ms"
        ),
    )
