# backend/app/core/risk_calculator.py
#
# ─── Provisional Heuristic Disclaimer ─────────────────────────────────────────
# This module implements a v1 rule-based simulation engine for flood-risk prediction.
#
# IMPORTANT: The thresholds, weights, and normalisation logic defined here are 
# unvalidated starting assumptions. They have not yet been calibrated against 
# empirical historical flood data. 
#
# Risk scores generated by this heuristic should be treated as simulation outputs
# for platform development and visualization purposes, NOT as ground-truth 
# life-safety predictions.
#
# ─── ML Abstraction Boundary ──────────────────────────────────────────────────
# This module is designed to be easily swappable. When the real Machine Learning
# model (e.g., Random Forest, LSTM) is trained and ready, simply replace the 
# internal logic of `calculate_risk_index` to invoke the ML inference pipeline. 
# The service layer (`predictive_engine.py`) and API routes will remain untouched.
# ──────────────────────────────────────────────────────────────────────────────

from typing import Tuple
from app.core.config import get_settings
from app.schemas.prediction import RiskLevel

def determine_risk_level(risk_index: float) -> RiskLevel:
    """
    Map a continuous risk index [0.0, 1.0] to a categorical RiskLevel Enum.
    """
    if risk_index < 0.25:
        return RiskLevel.LOW
    elif risk_index < 0.50:
        return RiskLevel.MODERATE
    elif risk_index < 0.75:
        return RiskLevel.HIGH
    return RiskLevel.CRITICAL


def calculate_risk_index(
    current_level: float,
    avg_level: float,
    elevation: float
) -> float:
    """
    Calculate a synthetic flood-risk probability score between 0.0 and 1.0.

    Inputs:
        current_level : The most recent water level reading (metres).
        avg_level     : The average water level over the recent time window.
        elevation     : The geographic elevation (metres), ideally from DEM.

    Calculation:
        1. Normalise current level against configured max expected level.
        2. Normalise trend (current - average) to capture sudden spikes.
        3. Normalise elevation vulnerability (lower elevation = higher risk).
           TODO (v2): Add spatial neighborhood comparison for depression detection 
           using PostGIS ST_DWithin to identify local sinks vs surrounding average.
        4. Apply configured weights to the three components.

    Returns:
        risk_index : A clamped float in the range [0.0, 1.0].
    """
    settings = get_settings()

    # 1. Normalise Current Water Level
    # Clamped between 0.0 and 1.0
    max_level = settings.max_water_level_meters
    norm_level = max(0.0, min(current_level / max_level, 1.0)) if max_level > 0 else 0.0

    # 2. Normalise Trend (Growth Rate)
    # Trend is the difference between current and average. 
    # Positive trend means water is rising. We normalise this delta relative to max_level.
    # Negative trends (receding water) contribute 0 to the risk trend component.
    trend_delta = current_level - avg_level
    norm_trend = max(0.0, min(trend_delta / max_level, 1.0)) if max_level > 0 else 0.0

    # 3. Normalise Elevation Vulnerability (Simplified v1)
    # We use global min/max elevation to calculate relative vulnerability.
    # An elevation closer to min_elevation yields a vulnerability closer to 1.0.
    elev_range = settings.max_elevation_meters - settings.min_elevation_meters
    if elev_range > 0:
        # Clamp elevation within the expected bounds
        clamped_elev = max(settings.min_elevation_meters, min(elevation, settings.max_elevation_meters))
        # Inverse mapping: lower elevation -> higher vulnerability
        norm_vuln = 1.0 - ((clamped_elev - settings.min_elevation_meters) / elev_range)
    else:
        norm_vuln = 0.5 # Fallback if range is 0

    # 4. Apply Weights
    # The sum of weights should ideally be 1.0, but we enforce clamping regardless.
    raw_risk = (
        (norm_level * settings.weight_water_level) +
        (norm_trend * settings.weight_trend) +
        (norm_vuln * settings.weight_elevation)
    )

    # Clamp the final result to [0.0, 1.0] safety boundary
    return max(0.0, min(raw_risk, 1.0))
